import Head from 'next/head';
import Image from 'next/image';
import { Inter } from '@next/font/google';
import styles from '../styles/Home.module.css';

import Clock from '../components/clock.tsx';
import Weather from '../components/weather.tsx';

const inter = Inter({ subsets: ['latin'] });

export default function Home() {
    let lon = '108.316673';
    let lat = '22.816669';

    return (
        <>
            <Head>
                <title>Kindle Clock</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className={styles.main}>
                <Clock />
                <Weather lat={lat} lon={lon} apiKey={'9f940550c293ed46ff4097e74d6a9c61'} />
            </main>
        </>
    );
}
